name: rag-backend
type: web

build:
  builder: dockerfile

ports:
  - port: 8000
    protocol: http

env:
  - key: PYTHON_VERSION
    value: "3.11"
  - key: PORT
    value: "8000"

healthcheck:
  http:
    path: /health
    port: 8000

regions:
  - fra

scaling:
  min: 1
  max: 1
